# Generated by Django 3.1.1 on 2020-09-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.IntegerField(verbose_name='Мастерство')),
                ('stamina', models.IntegerField(verbose_name='Выносливость')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_skill', models.IntegerField(verbose_name='Текущее значение мастерства')),
                ('max_skill', models.IntegerField(verbose_name='Максимальное значение мастерства')),
                ('current_stamina', models.IntegerField(verbose_name='Текущее значение выносливости')),
                ('max_stamina', models.IntegerField(verbose_name='Максимальное значение выносливости')),
                ('current_luck', models.IntegerField(verbose_name='Текущее значение удачи')),
                ('max_luck', models.IntegerField(verbose_name='Максимальное значение удачи')),
                ('name', models.CharField(max_length=20)),
                ('provisions', models.IntegerField(default=10)),
                ('potion_skill', models.BooleanField(default=False, verbose_name='Напиток Мудрых')),
                ('potion_luck', models.BooleanField(default=False, verbose_name='Напиток Сильных')),
                ('potion_stamina', models.BooleanField(default=False, verbose_name='Напиток Удачливых')),
            ],
        ),
    ]
