# Generated by Django 3.1.1 on 2020-09-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labirint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='name',
            field=models.CharField(default=None, max_length=20, verbose_name='Название противника'),
            preserve_default=False,
        ),
    ]
