# Generated by Django 3.1.1 on 2020-09-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labirint', '0003_auto_20200929_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.AlterModelOptions(
            name='enemy',
            options={'verbose_name': 'Враг', 'verbose_name_plural': 'Враги'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.RemoveField(
            model_name='player',
            name='potion_luck',
        ),
        migrations.RemoveField(
            model_name='player',
            name='potion_skill',
        ),
        migrations.RemoveField(
            model_name='player',
            name='potion_stamina',
        ),
        migrations.AddField(
            model_name='page',
            name='enemy',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='labirint.enemy', verbose_name='Враг'),
        ),
        migrations.AddField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=0, verbose_name='Количество монет'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя игрока'),
        ),
        migrations.AlterField(
            model_name='player',
            name='provisions',
            field=models.IntegerField(default=10, verbose_name='Количество провизии'),
        ),
    ]
