# Generated by Django 3.1.1 on 2020-09-29 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labirint', '0004_auto_20200929_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='enemy',
        ),
        migrations.AddField(
            model_name='page',
            name='enemy_one',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enemy_one', to='labirint.enemy', verbose_name='Первый враг'),
        ),
        migrations.AddField(
            model_name='page',
            name='enemy_two',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enemy_two', to='labirint.enemy', verbose_name='Второй Враг'),
        ),
    ]
