# Generated by Django 3.1.1 on 2020-09-30 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labirint', '0006_auto_20200930_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ways',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labirint.page', verbose_name='Переход на')),
            ],
            options={
                'verbose_name': 'Путь',
                'verbose_name_plural': 'Пути',
            },
        ),
    ]
