# Generated by Django 3.1.1 on 2020-09-30 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labirint', '0007_ways'),
    ]

    operations = [
        migrations.AddField(
            model_name='ways',
            name='page_anchor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='labirint.page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ways',
            name='step',
            field=models.IntegerField(verbose_name='ID страницы перехода'),
        ),
    ]
