# Generated by Django 3.1.1 on 2020-10-06 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labirint', '0011_auto_20201002_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь в системе'),
        ),
    ]
