# Generated by Django 3.1.1 on 2020-10-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labirint', '0012_hero_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='User',
            new_name='user',
        ),
    ]
