# Generated by Django 3.1.1 on 2020-10-08 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labirint', '0016_auto_20201008_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='img',
            field=models.ForeignKey(default=26, on_delete=django.db.models.deletion.SET_DEFAULT, to='labirint.images'),
        ),
    ]
