# Generated by Django 3.1.1 on 2020-10-12 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labirint', '0017_enemy_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='Выбранный?'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='img',
            field=models.ForeignKey(default=26, limit_choices_to={'category__pk': 2}, on_delete=django.db.models.deletion.SET_DEFAULT, to='labirint.images', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='img',
            field=models.ForeignKey(limit_choices_to={'category__pk': 1}, on_delete=django.db.models.deletion.PROTECT, to='labirint.images', verbose_name='Картинка игрока'),
        ),
    ]
