# Generated by Django 3.1.1 on 2020-10-12 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labirint', '0018_auto_20201012_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='last_step',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='labirint.page', verbose_name='Последний переход'),
        ),
    ]
